### ISSUE TITLE
Must include version number in binary release filenames

### ISSUE THREAD

**Issue by EmbeddedMan** [chipKIT32/chipKIT-cxx#10]
There appears to be a flaw in the way the Arduino IDE handles files that are downloaded from the Boards Manager. It can't properly handle files that have the same name across multiple versions. For example, if you had pic32tools.zip for chipKIT-core v1.0.0 and pic32tools.zip (an updated version) for chipKIT-core v2.0.0, then if somebody tried to go from v2.0.0 to v1.0.0 they would not get the 'old' version of pic32tools.zip, because Arduino IDE thinks that it already has the file it needs, or it gives a CRC error because the file that it already has doesn't have the CRC of the other file.

So, please make sure that the binary files you upload to https://github.com/chipKIT32/chipKIT-compiler-builds have the compiler version number (v1.42.rc2 or whatever) in their actual filenames, so that they are always unique across all chipKIT-core versions.

**Comment by jasonkajita** [comment]
Updated filenames in v1.42.rc2 release https://github.com/chipKIT32/chipKIT-compiler-builds/releases/tag/1.42.rc.2
