### ISSUE TITLE
uint32_t& defined in a separate file causes compiler crash.

### ISSUE THREAD

**Issue by JacobChrist** [chipKIT32/chipKIT-cxx#11]
Test with the compiler included with chipKIT-core 1.3.1 on a Digilent WiFire board with MZ EFG silicone.  May not be an issue on an MX processor (not tested).

The attached chipKIT project demonstrates the issue.  Running this sketch causes the program to crash when trying to access ref_global3 or ref_global4.  The local references all work.

[compiler_bug_uint32_ref.zip](https://github.com/chipKIT32/chipKIT-cxx/files/586908/compiler_bug_uint32_ref.zip)

**Comment by jasonkajita** [comment]
Hi @JacobChrist, when you say "compiler crash", do you mean that you get a general exception when you run the sketch?

**Comment by JacobChrist** [comment]
I don't know if there is an exception.  The program output just hangs.  Is there a way to catch exceptions in the setup()?

Global references to a memory location defined in same file work as expected, but when the global reference is a different file the code just hangs.

Here is the output, it doesn't print ref_global3 or ref_global4, which are identical to ref_local3 and ref_local4:

Microchip XC32 complier bug: uint32 ref
ref_local1
AAAAAAAA
ref_local2
55555555
ref_local3
12345678
ref_local4
12345678
ref_global1
AAAAAAAA
ref_global2
55555555
ref_global3

**Comment by jasonkajita** [comment]
I see. It looks like the code is casting a char array to an int pointer. In the MIPS architecture (and many other RISC architectures), we can't cast pointers to other pointer types with a greater alignment requirement.

**Comment by JacobChrist** [comment]
I had that thought, too but the ref_local works and the global does not.

**Comment by JacobChrist** [comment]
Attached is a different version with less ref / deref going on.
[compiler_bug_uint32_ref.zip](https://github.com/chipKIT32/chipKIT-cxx/files/586932/compiler_bug_uint32_ref.zip)

**Comment by JacobChrist** [comment]
The explanation from Matt makes since, but the reason the compiler does this is a mystery since it should know that memory_map_hi is a uint8_t[][].

From Matt Jenkins:

When doing it locally the compiler knows what you are doing and uses byte accesses and all is fine. When you have the array in a separate file and just have uint32 references as far as the compiler is concerned you just have uint32s and uses word accesses. If those uint3ws aren't pointing ti a 4-byte boundary then all hell breaks loose.

**Comment by JacobChrist** [comment]
uint32_t& ref_global1 = *(uint32_t*)&memory_map_hi[0][0];

works,

uint32_t& ref_global1 = *(uint32_t*)&memory_map_hi[0][1];

does not...

Byte alignment from a different file... weird.

**Comment by JacobChrist** [comment]
Jason,

Is there a way to force byte alignment when the reference is defined in a separate file?

**Comment by jasonkajita** [comment]
You can do unaligned loads and stores using the tip described here: http://www.microchip.com/forums/FindPost/411896 Basically, you never want to cast a pointer of one type to a pointer of a type with greater alignment requirements.
